// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ShowSelectionLength
{
    internal sealed partial class Vsix
    {
        public const string Id = "c2ffcafd-dc47-4a4f-ba6b-07bcd6f2b0b6";
        public const string Name = "Show Selection Length";
        public const string Description = @"Shows the length of the editor text selection in the status bar";
        public const string Language = "en-US";
        public const string Version = "1.0.9993";
        public const string Author = "Mads Kristensen";
        public const string Tags = "selection, editor";
    }
}
